# Generated by Django 4.2.11 on 2024-06-07 23:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_masc', '0003_carritocompras_alter_producto_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=datetime.datetime.now)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosenCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.FloatField(blank=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto_masc.carrito')),
                ('codigodeBarras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto_masc.producto')),
            ],
        ),
    ]
