# Generated by Django 4.2.11 on 2024-06-02 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('fecha_creacion_categoria', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=25)),
                ('email_usuario', models.EmailField(max_length=25, unique=True)),
                ('password_usuario', models.CharField(max_length=10)),
                ('telefono_usuario', models.CharField(max_length=15, unique=True)),
                ('token_usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('bio_usuario', models.TextField(blank=True, null=True)),
                ('fotodeperfil_usuario', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('fecha_creacion_usuario', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subcategoria', models.CharField(max_length=100)),
                ('fecha_creacion_subcategoria', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion_producto', models.TextField()),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion_producto', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.categoria')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=255)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_historial_carrito', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_historial_carrito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_facturacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_facturacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_carrito_producto', models.PositiveIntegerField()),
                ('fecha_carrito', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.usuario')),
            ],
        ),
    ]
